# .github/release.yml

changelog:
  categories:
    - title: '❗ Breaking Changes'
      labels:
        - '❗ BreakingChange'
    - title: '🚀 New Features'
      labels:
        - '✏️ Feature'
        - '📝 Proposal'
    - title: '🧹 Updates'
      labels:
        - '🧹 Updates'
        - '⚡️ Performance'
    - title: '🐛 Bug Fixes'
      labels:
        - '☢️ Bug'
    - title: '🛠️ Maintenance'
      labels:
        - '🤖 Dependencies'
    - title: '📚 Documentation'
      labels:
        - '📒 Documentation'
    - title: 'Other Changes'
      labels:
        - '*'
  template: |
    ## Summary

    $CHANGES

    > ℹ️ All modules now use the Fiber v3 import path scheme `github.com/gofiber/contrib/v3/<module>`.
