name-template: 'v3/{{FOLDER}}/v1 - v$RESOLVED_VERSION'
tag-template: 'v3/{{FOLDER}}/v$RESOLVED_VERSION'
tag-prefix: v3/{{FOLDER}}/v
include-paths:
  - {{FOLDER}}
categories:
    - title: '❗ Breaking Changes'
      labels:
          - '❗ BreakingChange'
    - title: '🚀 New'
      labels:
          - '✏️ Feature'
    - title: '🧹 Updates'
      labels:
          - '🧹 Updates'
          - '🤖 Dependencies'
    - title: '🐛 Fixes'
      labels:
          - '☢️ Bug'
    - title: '📚 Documentation'
      labels:
          - '📒 Documentation'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
exclude-contributors:
    - dependabot
    - dependabot[bot]
version-resolver:
    major:
        labels:
            - 'major'
            - '❗ BreakingChange'
    minor:
        labels:
            - 'minor'
            - '✏️ Feature'
    patch:
        labels:
            - 'patch'
            - '📒 Documentation'
            - '☢️ Bug'
            - '🤖 Dependencies'
            - '🧹 Updates'
    default: patch
template: |
    Package path: `github.com/gofiber/contrib/v3/{{FOLDER}}/v1`

    $CHANGES

    **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v3/{{FOLDER}}/v$RESOLVED_VERSION

    Thank you $CONTRIBUTORS for making this update possible.
