# .github/release.yml

changelog:
  categories:
    - title: '❗ Breaking Changes'
      labels:
        - '❗ BreakingChange'
    - title: '🚀 New Features'
      labels:
        - '✏️ Feature'
        - '📝 Proposal'
    - title: '🧹 Updates'
      labels:
        - '🧹 Updates'
        - '⚡️ Performance'
    - title: '🐛 Bug Fixes'
      labels:
        - '☢️ Bug'
    - title: '🛠️ Maintenance'
      labels:
        - '🤖 Dependencies'
    - title: '📚 Documentation'
      labels:
        - '📒 Documentation'
    - title: 'Other Changes'
      labels:
        - '*'
  template: |
    ## Summary

    $CHANGES

    > ℹ️ Each module now increments its Go module major version for Fiber v3 support. Import it via `github.com/gofiber/contrib/<module>/vN`, replacing `vN` with the new major (for example, `v2` or `v3`).
