name: "Test Prometheus"

on:
  push:
    branches:
      - master
      - main
    paths:
      - "prometheus/**"
  pull_request:
    paths:
      - "prometheus/**"

jobs:
  Tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.21.x
          - 1.22.x
          - 1.23.x
          - 1.24.x
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ matrix.go-version }}"
      - name: Run Test
        working-directory: ./prometheus
        run: go test -v -race ./...
